/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  purge: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./sections/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      'xs': { 'max':    "576px" },
      'sm': { 'min':    "640px" },
      'md': { 'min':    "768px" },
      'lg': { 'min':    "1024px" },
      'xl': { 'min':    "1280px" },
      '2xl': { 'min':   "1536px" }
    },
    extend: {
      colors: {
        'eugen': {
          'primary':                  "#b3e3fc",
          'primary-dark':             "#081B33",
          'secondary':                "#03b8fc",
          'secondary-hover':          "#029cd6",
          'secondary-focus':          "#01638a",
          'secondary-dark':           "#00719c",
          'secondary-hover-dark':     "#008ec4",
          'secondary-focus-dark':     "#004059",
          'accent':                   "#ffdd4a",
          'accent-hover':             "#fcd83d",
          'accent-dark':              "#eca400",
          'accent-hover-dark':        "#faae02",
          'highlight':                "#ffd166",
          'inverted':                 "#ffffff",
          'inverted-muted':           "#dee7ea",
          'neutral':                  "#c00021",
          'neutral-muted':            "#dee7ea",
        },
        'kris': {
          'primary':                  "#ffc6bd",
          'primary-dark':             "#59052c",
          'secondary':                "#eeeeee",
          'secondary-dark':           "#eeeeee",
          'accent':                   "#ffd166",
          'inverted':                 "#ffffff",
          'inverted-muted':           "#dee7ea",
          'neutral':                  "#dee7ea",
          'neutral-muted':            "#dee7ea",
        },
      },
    },

    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
